### ISSUE TITLE
Autoloader breaks on class_exists

### ISSUE THREAD

**Issue by peterjaap** [theiconic/php-ga-measurement-protocol#50]
```
Warning: include(TheIconic\Tracking\GoogleAnalytics\Parameters\EnhancedEcommerce\TransactionIdCollection.php): failed to open stream: No such file or directory  in /data/elgentos/clientname/magento/app/code/community/Varien/Autoload.php on line 136

#0 /data/elgentos/clientname/magento/app/code/community/Varien/Autoload.php(136): mageCoreErrorHandler(2, 'include(TheIcon...', '/data/elgentos/...', 136, Array)
#1 /data/elgentos/clientname/magento/app/code/community/Varien/Autoload.php(136): include()
#2 [internal function]: Varien_Autoload->autoload('TheIconic\\Track...')
#3 [internal function]: spl_autoload_call('TheIconic\\Track...')
#4 /data/elgentos/clientname/vendor/theiconic/php-ga-measurement-protocol/src/Analytics.php(809): class_exists('\\TheIconic\\Trac...')
#5 /data/elgentos/clientname/vendor/theiconic/php-ga-measurement-protocol/src/Analytics.php(891): TheIconic\Tracking\GoogleAnalytics\Analytics->getParameter('getTransactionI...', Array)
#6 /data/elgentos/clientname/magento/app/code/community/Elgentos/ServerSideAnalytics/Model/GAClient.php(103): TheIconic\Tracking\GoogleAnalytics\Analytics->__call('getTransactionI...', Array)
#7 /data/elgentos/clientname/magento/app/code/community/Elgentos/ServerSideAnalytics/Model/Observer.php(82): Elgentos_ServerSideAnalytics_Model_GAClient->firePurchaseEvent()
#8 /data/elgentos/clientname/magento/app/code/core/Mage/Core/Model/App.php(1358): Elgentos_ServerSideAnalytics_Model_Observer->sendPurchaseEvent(Object(Varien_Event_Observer))
#9 /data/elgentos/clientname/magento/app/code/core/Mage/Core/Model/App.php(1337): Mage_Core_Model_App->_callObserverMethod(Object(Elgentos_ServerSideAnalytics_Model_Observer), 'sendPurchaseEve...', Object(Varien_Event_Observer))
#10 /data/elgentos/clientname/magento/app/Mage.php(456): Mage_Core_Model_App->dispatchEvent('test_event_for_...', Array)
#11 /data/elgentos/clientname/magento/app/design/frontend/clientname/default/template/page/homepage.phtml(46): Mage::dispatchEvent('test_event_for_...', Array)
#12 /data/elgentos/clientname/magento/app/code/core/Mage/Core/Block/Template.php(241): include('/data/elgentos/...')
#13 /data/elgentos/clientname/magento/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('frontend/clientn...')
#14 /data/elgentos/clientname/magento/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#15 /data/elgentos/clientname/magento/app/code/local/Mage/Core/Block/Abstract.php(919): Mage_Core_Block_Template->_toHtml()
#16 /data/elgentos/clientname/magento/app/code/local/Inchoo/PHP7/Model/Layout.php(15): Mage_Core_Block_Abstract->toHtml()
#17 /data/elgentos/clientname/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(390): Inchoo_PHP7_Model_Layout->getOutput()
#18 /data/elgentos/clientname/magento/app/code/core/Mage/Cms/Helper/Page.php(137): Mage_Core_Controller_Varien_Action->renderLayout()
#19 /data/elgentos/clientname/magento/app/code/core/Mage/Cms/Helper/Page.php(52): Mage_Cms_Helper_Page->_renderPage(Object(Mage_Cms_IndexController), 'home')
#20 /data/elgentos/clientname/magento/app/code/core/Mage/Cms/controllers/IndexController.php(45): Mage_Cms_Helper_Page->renderPage(Object(Mage_Cms_IndexController), 'home')
#21 /data/elgentos/clientname/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Cms_IndexController->indexAction()
#22 /data/elgentos/clientname/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('index')
#23 /data/elgentos/clientname/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#24 /data/elgentos/clientname/magento/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#25 /data/elgentos/clientname/magento/app/Mage.php(691): Mage_Core_Model_App->run(Array)
#26 /data/elgentos/clientname/magento/index.php(83): Mage::run('', 'store')
#27 {main}
```

**Comment by peterjaap** [comment]
See #51

**Comment by jorgeborges** [comment]
Thanks, merging and releasing now.
